sudo: required
services:
  - docker

language: node_js

node_js:
  - "5"

git:
    submodules: false

env:
  global:
    - secure: "UnkjMMD5WA19zORlk1LECpO1GZfWvuM0WcVmougiuwlQhTPv697UMA1NEmTXNzMgF5DTEHNaBiIr9Q75woOzXnjJsTizsyUpwAQHP//s6ZTfuof3EUAQg3rX9tGj/KFHG3VuvDOlCnF6R1hc86jLTRL61DiWP/4+Q9Wn8JXeicPS2eI8ga+fVyTvgLtYZ//e+egyYK32dZyqvT0mlfFEpLBnMVmYzzi9SSHBu2otLLTvEray90V2afNamiqvb4Wwc9hGJF4fLZfMF8vuPqFztnA2imOdCtd1D3PZ6tNp3cXalqggn6aqkXwDoCZzmO3CHfLqIEqZuCeas0bwccApu5ZL14b/b618jwU9hoXhFHr+eZZxjoYqD0wRyJFH2fxbOWPzXJ05fpwY2s5Avflh7g1qhDmPsqc/O9SyplKqSvCeXdf+im/fesbZuzU1dDqX8ZXQFY4EK4ye+fORWzda/0Ltc0HMBVB44kz7wXbYlYT+10IqUZH7xidRVTAWRjpvUD1UzrJFr6N/WA2CQXUBr/VHbi23kVPoysZaZxZ2f9frfp0NNfUflMQhiKYiFuPf7D7j4DVLUX0QlUpmhTTGUsdodNpgTbvTszf7+vRHgLa4FbESn/ISbtOaFyIvqYTssezo8KAUrK50ABWKH0kt3VFydRQ61Qab5slVDl+NOBo="
    - secure: "F2TFYlVRGMb7u95e2wO8s1sG2ChZm/R3a2rxymXTcAif6m9ocpI6M7pWhgfLzR+ZHb9AOgCpbn0NcDHHSuBgYQjmwFV9BLcQ18/pKNIyP+Ei6kqJYMv5f7XAIm0/7DlpH28iHuyn5Fe/O027ItPg9fCDkqL2GjMn4dvmEYUAUmGkLmAWKZKz5lLNryLTDsB4ZaLWD+kUpVyYBixIk6cu02VMatc5v26tiRfVQsFvtpsETKGJPtoN+S1VEcB4/OBdodBXKtwAIOLw1x0DcIpTqD/UcTGyrS/P0H+47YuMnZ5d1l+KynCJiOy7OS12/5ViRbt9RAP2H2bit1s/FGZ2dvJAIXEgm9LRO3ewZaJWIQ90H0UywXU2NT42w6t+Brm15+3IxOJzJ1kFxSiule547NtCiookfY8Dypo3RPE33VI+z8W7ZjrgtU08pvzpZmrgHn3vsl8OCoDm4BRs/HUfWkxQAbr3jNVe8uSxsgDLDnAYN3/+luUnZkD7RAsHAiqi4EBFKlvaLYhsN+nD+V/cw5+DqEUyyF+7e3haK/AYzVP5z0r/5C5jqEp1dGGehJZJ1apyclFpMtDGmwt04GeSPldFTHgP2HSyNy2V1/pQMn+TcIHdajAticaXYWF3wSjt3TWxTD6bPxyiYNUTO/SQ780ddbt2hYKT271tNyPFyEQ="
    - secure: "eWiQ3SMI91oYuoHQpCeImDa+X29wbJJCk8LrRdhuKXNanW9eF8zfwBCmycxjSNFl4OcWzEs8EUBym1tj+hzQ41DEFV57svShB6Sw+R5zDwUwd1JigNvbtEZXLY6kURrKEqwMT3zyPi5ndGf6gl12hDByoa0HNBgYeDNs/MepogOmRVpUIlMBMZeq8IxQZOaG3DKP05zPHhSaM/jTt3EGkThUAElXvzpjFCr6z8JzKepxXKK2sctodrRQ8OwR4CPghUkDm9BvNixP06eM8tLsAThVlQg3Dt/fwtCteHhyN+axfBNJr36Sd6xg87g2DTK79L7KXRfKbMrH38gG5W8aCr4NOuer4U+2wHQ8KBJg/HyagdiS1x+Pih01TB9H8scepSx/TLqqtlu/VgFjC5lDclYZiKEkYfWIhDOPoVUq2N/8wCiuPHEDumS5xRcqlkK0+o+0J7Ell/g6GCB28wbJV2kme/AbwGFrlrLdE9SzszaAgFRNbHG6t1o/WuqPfRcyKbyM+L6NrCbGbmxNPwPgKyGYKUfaqdGMLABsc/EXvgKTkt/jUptyjNLPMw5JPYcJxw2frmok8O+IsL3qVcKhqW/6XUmR5LdoaLilNf7DpxkyTqwzC9TFfmc86v2TBuSz4CabkUYI5sIddbLJ1By7BpQrmjxijt/u1ksPYxYF0FY="
    #- secure: "jkrBWm8/ZcFKGElYxKuOxAQkjAYXdgupp26VIy6TI2p1nJ4syjnOU1MTZ8CulGhlte/ehIMuvsiz0VlpTTh8yZzJLmFim6VXBryILam7uXh5hDo2ypcVXeBRqE7Uc63Bq6rfYPm4otHJ1fbhFixuh5JGwYD1TOoN6hldkR8JV5m+1V9UKuicxVALnVHl0begjsug4YsfKw9zIIM+/tlr4AcUX9REKz6KRhguV7sA7T8B+apaAWhIIpPyjwcHGKk9x+beOD5jFFGsaq4O5kBFzFmEiLBPRiOUeKM8enHLM/7UQjPnz1Ivz3yFb2FlQ2lhEIPKLVFDOjf/n6r7D8j+PHeTRRlo5UkRLN8p1nkglJwTImsmDPRpdT1+hXuSlh1WKOwez9eFaEUwnjhBTTFDW1G50VcsBE1yPltMr3PcrWLw6/J2+uzbyJOF25jMWG65D9QLKgih8PvvUimin1kYIkkcUsIQoL94WjeaNIV1WWXE8InvH+9YgwqRDukGClJoOQl0KxTRvV4jaiFrVDigt911JpDSLSRX6WK2iS1Z+/NCcThDe9GTaSrz5KoXZTE6qIO6KX/duj9HOON2iO0ywsc2JQZXyY0snGjulbLyDCN6YjFsjxLUbprT04fp3quTt3+NiM4U/6dpADmm3yXWUE1ek/VznvA7sd2cHn0txfs="
    - secure: "oBgtm8kSeZAuDC++IWV+dGLL+XS303M5eN7zKIvmV4F6IMUawFSoZhY9kG8jsIysAjXbJ4j5Rva/OuYx2fzVX6wpg3zn5sWjCUN1GamVpJt7P/j5A0e0S+3C/EI4R0CMBuvCSSXu7jD4PKkSCCku4WqRgVPhoyIyILPTnITi1rAcSzerQffup0DEvfDLxml8MfJM7Jp3jY8kWhkL1p6A1Tr8gFO0hz5vwGEE+gQovXSK4OuFA1BQjUVcwdLbA3k+Df3449JETi+H4/YOeHaSTEb0kmPRj+2mAfBhLLADQCoylmM6lTvomuHm7cDXttuYowO+8GGCSQ1JDUV4u9gIP4sUQvHZcjqb0YdMvleB5Z9HJQmMVDxV1yEhFGZPcaQ+ti65esJJJQ75BBaWcFs72s7HPz41LnHgIlAfdzfRlrg8gQlh4f7+V2ieWJUeDSXtDZG4WIEtJ6W4v3bizfrv1hImRRNA5+APonx76VCgNZgzlAqnL7zgWYFnnZGM4EgA33Q36Rwg97UX3oiNweprQE32yiO4XkWrLFZKpYfmoqCryWZKvTHAzE5k6NmIeTPESlOQ3uhrVFUaE5QLkIQzaWXt9rfJix6IGgEzfEchhrqYsPdxXDO7ySU2VLR+g8ryhXclFaqI/9XOCF1J8O1fJB8sIfheh53tJ6xF+PpZzu4="



before_install:
    - cat .gitmodules
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - cat .gitmodules
    - git submodule update --init --recursive

before_script:

  - cd code/api
  - npm install
  - cd ../ui
  - npm install
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - gulp
  - cd ..


script:
  - echo ">>>>> Running core tests<<<<<"
  - npm test
  - echo ">>>>> Running UI tests<<<<<"
  - cd ui
  - npm test
  - cd ..


after_success:

  - echo ">>>>> Updating Dev fork <<<<<"
  - git remote add upstream https://DinisCruz-Dev:$git_pwd@github.com/DinisCruz-Dev/Maturity-Models.git
  - git push -f upstream

  - echo ">>>>> Building DOCKER IMAGE and pushing it go Docker Hub <<<<<"
  - echo 'building docker image'
  - docker images
  - docker build -t diniscruz/maturity-models .
  - docker images
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker push diniscruz/maturity-models

#  - echo ">>>>> Cloning Maturity-Models-QA, adding extra commit and pushing it to Maturity-Models-Dev for  <<<<<"
#  - cd ..
#  - git clone https://github.com/DinisCruz/Maturity-Models-QA.git
#  - cd Maturity-Models-QA
#  - git remote add upstream https://DinisCruz-Dev:$git_pwd@github.com/DinisCruz-Dev/Maturity-Models-QA.git
#
#  - git config --global user.email "bot@travis.com"
#  - git config --global user.name "Travis Bot"
#
#  - git log -n5 --pretty=oneline > travis-git-log.txt
#  - git add .
#  - git commit -m "Comming files for $(git rev-parse HEAD)"
#  - git push --quiet -f upstream master